[project]
name = "dearpypixl"
version = "1.2.0"
description = "An object-oriented, lightweight, modular framework and toolkit for Dear PyGui."
authors = [{name="Anthony Doupe", email="atlamillias@outlook.com"}]
keywords = ["dearpygui", "gui", "ui", "user-interface"]
urls = {Homepage="https://github.com/Atlamillias/DearPyPixl"}
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",

    "Operating System :: Microsoft :: Windows :: Windows 8.1",
    "Operating System :: Microsoft :: Windows :: Windows 10",
    "Operating System :: Microsoft :: Windows :: Windows 11",
    "Operating System :: MacOS",
    "Operating System :: POSIX",
    "Operating System :: Unix",

    "License :: OSI Approved :: MIT License",
]
requires-python = ">=3.10"
dependencies = [
    "dearpygui >= 1.9.0",
    "typing-extensions; python_version < '3.12'",
]


[build-system]
requires = ["setuptools ~= 65.0", "wheel"]
build-backend = "setuptools.build_meta"


[tool.setuptools]
packages = [
    "dearpypixl",
]
include-package-data = true

[tool.setuptools.package-data]
dearpypixl = ["*.typed", "*.pyi"]

